### PR TITLE
Propagate stacktrace

### LINKED ISSUE #7: Incorporate Chain.capture
Have you heard of Chain.capture @ [stack_trace](https://pub.dev/packages/stack_trace)

The problem that it might solve (unless I'm missing something) is that if an exception were to be thrown inside of a Handler. The most relevant line that is shown in the stacktrace is the actor.send call. I hope Chain.capture could fix that and display the root of the cause (the line that throws the exception inside of the handler)

I was not successful in wrapping the actor and the .send call with a Chain.capture. Is it even possible to do that across isolates? 
If not, could a StackTrace be passed back by a faulty isolate and be chained onto the current isolates StackTrace?

_And thank you for the great library. This is one of those hidden gems that one day probably everybody will have to use in one form or another :)_

### PR DESCRIPTION
**Pull request by modulovalue**
To my surprise, this was enough to fix #7

### CODE REVIEW

File: lib/src/actors_base.dart [hunk 1]
```diff
@@ -11,8 +11,11 @@ class _Message {
   final int id;
   final content;
   final bool isError;
+  final String stackTraceToStringOrNull;
```
Comment (renatoathaydes) [inline lib/src/actors_base.dart]: Great that this is actually possible!! Will  try it soon and merge if no problems are found.
Can I just ask you to please not name the variable with `orNull` at the end?

Soon Dart will finally get nullable types anyway, so this will become a `String?` :)

Comment (renatoathaydes) [reply lib/src/actors_base.dart]: In fact, I would suggest naming it `stackTraceAsString` as that makes it clearer IMO what it is.

**Review by renatoathaydes — CHANGES_REQUESTED** [review]

File: lib/src/actors_base.dart (hunk 1 above)
Comment (modulovalue) [reply lib/src/actors_base.dart]: > In fact, I would suggest naming it stackTraceAsString as that makes it clearer IMO what it is.

I do not agree and yes orNull will not be necessary as soon as nnbd lands but I'll make the change.

Also, it's called stackTraceToString because it is literally the toString version of the StackTrace which is the only representation that can be translated back into a StackTrace. asString tells the consumer it's just a string and nothing else.

Edit: using that argumentation perhaps stackTraceAsToString would be more fitting.

**Comment by modulovalue** [comment]
[StackTrace.fromString](https://api.flutter.dev/flutter/dart-core/StackTrace-class.html) it's called stackTraceString here so i hope that's fine.

File: lib/src/actors_base.dart (hunk 1 above)
Comment (renatoathaydes) [reply lib/src/actors_base.dart]: The problem with `stackTraceToString` it that it uses a known pattern: `xToY` is a pattern used by conversion functions from x to y.
`asString` tells that it is a type converted to a String, which is the exact meaning here.

**Comment by renatoathaydes** [comment]
yeah, that's perfect :)

File: lib/src/actors_base.dart (hunk 1 above)
Comment (modulovalue) [reply lib/src/actors_base.dart]: Of course, conventions take precedence over vague contextual information. Thank you for the clarification I failed to consider that.

**Comment by renatoathaydes** [comment]
I've had to make some changes so that the stacktrace works in StreamActor as well, and added tests to verify it.
It's now merged. Thanks @modulovalue !
